/* Automatically generated by configure - do not modify */
/* Copied by meson to avoid running ./configure as it is not needed */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 0
#endif
#define TCC_VERSION "0.9.28rc"
#define GCC_MAJOR 14
#define GCC_MINOR 2
#define CC_NAME CC_gcc
