#!/bin/env bash
# Not portable, but it works for now. Needed to use the actual installed version.
# VS_PREFIX_DIR must point to the base root of where you are placing the distribution files.

export VS_COMMONS_DIR="$VS_PREFIX_DIR/usr/local/share/vs-fltk/"
export PATH="$VS_PREFIX_DIR/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$VS_PREFIX_DIR/usr/local/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$VS_PREFIX_DIR/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export MANPATH=$VS_PREFIX_DIR/usr/local/share/man:$MANPATH;
export INFOPATH=$VS_PREFIX_DIR/usr/local/share/man:$INFOPATH;

vs "$@"